#!/usr/bin/env bash
# This script displays the contents of the file `/etc/passwd`.
# It only displays the username, user id

file_u="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$file_u"
