#!/usr/bin/env bash

# This script reads the /etc/passwd file and displays the username,
# user ID, and home directory path for each user


while read -r line; do
    fields="($line)"

    username=${fields[0]}
    uid=${fields[2]}
    home_dir=${fields[5]}

    echo "$username:$uid:$home_dir"
done < /etc/passwd
 
