#!/usr/bin/env bash
#This script tells a story based on the contents of the `/etc/passwd` file
file_u="/etc/passwd"
fls1=""
fls2=""
fls3=""
while IFS= read -r line
do
    fls1="$(echo "$line" | cut -d":" -f1)"
    fls2="$(echo "$line" | cut -d":" -f4)"
    fls3="$(echo "$line" | cut -d":" -f6)"
    fls4="$(echo "$line" | cut -d":" -f7)"
    fls5="$(echo "$line" | cut -d":" -f3)"
    fls6="$(echo "$line" | cut -d":" -f2)"
    fls7="$(echo "$line" | cut -d":" -f5)"
    echo "The user ${fls1} is part of the ${fls2} gang, lives in ${fls3} and rides ${fls4}. ${fls5}'s place is protected by the passcode ${fls6}, more info about the user here: ${fls7}"
done < "$file_u"
