#!/usr/bin/env bash
# This script displays the contents of the current directory in a list format,
# where only the part of the name after the first dash is displayed

for file in *
do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]
    then
        echo "${file#*-}"
    fi
done
